name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Make deploy.sh Executable
        run: chmod +x deploy.sh

      - name: Run deploy.sh
        run: ./deploy.sh